apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordermgr
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ordermgr
    spec:
      containers:
      - name: ordermgr 
        image: jotak/kubeotprom-ordermgr:latest
        ports:
        - name: web
          containerPort: 8080
        - name: prometheus-jmx
          containerPort: 9099
        env:
          - name: JAEGER_SERVICE_NAME
            value: ordermgr
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: ACCOUNTMGR_URL
            value: "http://accountmgr:8080"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
---
apiVersion: v1
kind: Service
metadata:
  name: ordermgr
  labels:
    app: ordermgr
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ordermgr
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  name: ordermgr
spec:
  to:
    kind: Service
    name: ordermgr
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accountmgr
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: accountmgr
    spec:
      containers:
      - name: accountmgr 
        image: jotak/kubeotprom-accountmgr:latest
        ports:
        - name: web
          containerPort: 8080
        - name: prometheus-jmx
          containerPort: 9099
        env:
          - name: JAEGER_SERVICE_NAME
            value: accountmgr
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
---
apiVersion: v1
kind: Service
metadata:
  name: accountmgr
  labels:
    app: accountmgr
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accountmgr
  type: ClusterIP
