apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordermgr
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ordermgr
    spec:
      containers:
      - name: ordermgr 
        image: jpkroehling/kubeotprom-ordermgr:0.0.1
        ports:
        - name: web
          containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: ordermgr
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: ACCOUNTMGR_URL
            value: "http://accountmgr:8080"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
---
kind: Service
apiVersion: v1
metadata:
  name: ordermgr
  labels:
    app: ordermgr
spec:
  type: LoadBalancer
  selector:
    app: ordermgr
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accountmgr
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: accountmgr
    spec:
      containers:
      - name: accountmgr 
        image: jpkroehling/kubeotprom-accountmgr:0.0.2
        ports:
        - name: web
          containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: accountmgr
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
---
kind: Service
apiVersion: v1
metadata:
  name: accountmgr
  labels:
    app: accountmgr
spec:
  type: LoadBalancer
  selector:
    app: accountmgr
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
